services:
  nginx:
    build: ./images/nginx
    image: compose-nginx
    ports:
      - 80:80
    volumes:
      - ../projects:/var/www
      - ../configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../configs/nginx/sites:/etc/nginx/sites-available
      - ../configs/nginx/sites:/etc/nginx/sites-enabled
    # depends_on:
    #   - php
    networks:
      - app_network
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 200M

  php:
    build: ./images/php
    image: compose-php
    user: 1000:1000
    volumes:
      - ../projects:/var/www
      - ../configs/php/php.ini:/usr/local/etc/php/php.ini
      - ../configs/php/xdebug.ini:/usr/local/etc/php/xdebug.ini
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    networks:
      - app_network
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 200M

networks:
  app_network:
    external: true