services:
  unit:
    image: unit:php8.3
    # ports:
    #   - 80:8080
    networks:
      - app_network
    volumes:
      - ../configs/php/unit.json:/docker-entrypoint.d/config.json
      - ../projects:/www
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M
        reservations:
          cpus: '0.1'
          memory: 200M

  # unit_cms:
  #   image: unit:php8.3
  #   ports:
  #     - 81:81
  #   networks:
  #     - app_network
  #   volumes:
  #     - ../configs/php/unit.laravel.json:/docker-entrypoint.d/config.json
  #     - ../projects/cms:/www
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.1'
  #         memory: 500M
  #       reservations:
  #         cpus: '0.1'
  #         memory: 200M

networks:
  app_network:
    external: true