services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80" 
      - "443:443"
    networks:
      - app_network
    volumes:
      - ../configs/caddy/Caddyfile:/etc/caddy/Caddyfile
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 60s
      resources:
        reservations:
          cpus: '0.1'
          memory: 200M

networks:
  app_network:
    external: true